language: node_js
node_js:
- '8'
dist: trusty
sudo: required
addons:
  chrome: stable
  ssh_known_hosts: web0101.zxcs.nl
branches:
  only:
  - master
before_script:
- npm install -g @angular/cli
script:
- ng build --prod --aot
- xvfb-run -- ng test --watch false
deploy:
  provider: script
  skip_cleanup: true
  script: npm run deploy
  on:
    branch: master
before_deploy:
- openssl aes-256-cbc -K $encrypted_65c53eddb66f_key -iv $encrypted_65c53eddb66f_iv
  -in vimexx_travis_openssh.enc -out vimexx_travis_openssh -d
