language: node_js
node_js:
  - "8"

sudo: required
addons:
  chrome: stable

branches:
  only:
  - master

before_script:
  - npm install -g @angular/cli

script:
  - ng build --prod --aot
  - ng test --watch false
